version = 1
SPDX-PackageName = "nomos-studio"
SPDX-PackageSupplier = "rodgert@twrodgers.com"
SPDX-PackageDownloadLocation = "https://github.com/nomos-studio/nomos-studio"

[[annotations]]
path = ["bin/**", "scripts/**", "docs/**", "doc/**",
        "README.md", "install.sh", "components.lock", ".gitignore",
        "CMakeLists.txt", "CMakePresets.json", "Makefile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 nomos-studio contributors"
SPDX-License-Identifier = "EPL-2.0"

# CI workflows
[[annotations]]
path = [".github/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 nomos-studio contributors"
SPDX-License-Identifier = "EPL-2.0"
